[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[phases.start]
cmd = "cd backend && python manage.py runserver 0.0.0.0:$PORT"
