FROM node:18-alpine

# Set work directory
WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy project
COPY . /app/

# Change to frontend directory
WORKDIR /app/frontend

# Expose port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
