version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: phoenix_knowledge_engine
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: 
      context: .
      dockerfile: infrastructure/Dockerfile
    command: cd backend && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://phoenix:phoenix_password@db:5432/phoenix_knowledge_engine
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.frontend
    command: cd frontend && npm start
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app

volumes:
  postgres_data:
